# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icleaner < Formula
  desc "Open-source macOS CLI disk cleaner"
  homepage "https://github.com/grkndev/ICleaner"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grkndev/ICleaner/releases/download/v0.3.1/ICleaner_0.3.1_darwin_amd64.tar.gz"
      sha256 "9f7f85ed205d5c462d59aa7a792fd8bb9e037b4d752a0837d1d35d9c5eeda9fe"

      define_method(:install) do
        bin.install "icleaner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grkndev/ICleaner/releases/download/v0.3.1/ICleaner_0.3.1_darwin_arm64.tar.gz"
      sha256 "fbff50cf6a82cc772d1e4ae9e40df4bcb865efce039c26669d3b744127f3b18e"

      define_method(:install) do
        bin.install "icleaner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grkndev/ICleaner/releases/download/v0.3.1/ICleaner_0.3.1_linux_amd64.tar.gz"
      sha256 "461c932ff333147912dab56a8a22a9ac7708e29899780eb7faaabe0673fce1d0"
      define_method(:install) do
        bin.install "icleaner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grkndev/ICleaner/releases/download/v0.3.1/ICleaner_0.3.1_linux_arm64.tar.gz"
      sha256 "9f2c4f95337729e72d7daa70e7d5b4403225249dce5b421c2cad26dbedb1084a"
      define_method(:install) do
        bin.install "icleaner"
      end
    end
  end
end
